const POST_ACTION_TYPES = {
  GET_POSTS_START: 'post/GET_POSTS_START',
  GET_POSTS_SUCCESS: 'post/GET_POSTS_SUCCESS',
  GET_POSTS_FAILED: 'post/GET_POSTS_FAILED',
};

export default POST_ACTION_TYPES;
