const POST_ACTION_TYPES = {
  GET_POSTS_START: 'post/GET_POSTS_START',
  GET_POSTS_SUCCESS: 'post/GET_POSTS_SUCCESS',
  GET_POSTS_FAILED: 'post/GET_POSTS_FAILED',

  CREATE_POST_START: 'post/CREATE_POST_START',
  CREATE_POST_SUCCESS: 'post/CREATE_POST_SUCCESS',
  CREATE_POST_FAILED: 'post/CREATE_POST_FAILED',

  LIKE_POST_START: 'post/LIKE_POST_START',
  LIKE_POST_SUCCESS: 'post/LIKE_POST_SUCCESS',
  LIKE_POST_FAILED: 'post/LIKE_POST_FAILED',

  UNLIKE_POST_START: 'post/UNLIKE_POST_START',
  UNLIKE_POST_SUCCESS: 'post/UNLIKE_POST_SUCCESS',
  UNLIKE_POST_FAILED: 'post/UNLIKE_POST_FAILED',

  COMMENT_ON_POST_START: 'post/COMMENT_ON_POST_START',
  COMMENT_ON_POST_SUCCESS: 'post/COMMENT_ON_POST_SUCCESS',
  COMMENT_ON_POST_FAILED: 'post/COMMENT_ON_POST_FAILED',
};

export default POST_ACTION_TYPES;
