const ME_ACTION_TYPES = {
  UPDATE_ME_START: 'me/UPDATE_ME_START',
  UPDATE_ME_SUCCESS: 'me/UPDATE_ME_SUCCESS',
  UPDATE_ME_FAILED: 'me/UPDATE_ME_FAILED',

  GET_MY_POST_START: 'me/GET_MY_POST_START',
  GET_MY_POST_SUCCESS: 'me/GET_MY_POST_SUCCESS',
  GET_MY_POST_FAILED: 'me/GET_MY_POST_FAILED',
};

export default ME_ACTION_TYPES;
