const USER_ACTION_TYPES = {
  SET_TOKEN: 'user/SET_TOKEN',
  LOGIN_START: 'user/LOGIN_START',
  LOGIN_SUCCESS: 'user/LOGIN_SUCCESS',
  LOGIN_FAILED: 'user/LOGIN_FAILED',
  SIGNUP_START: 'user/SIGNUP_START',
  SIGNUP_SUCCESS: 'user/SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'user/SIGNUP_FAILED',
  LOGOUT_START: 'user/LOGOUT_START',
  LOGOUT_SUCCESS: 'user/LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'user/LOGOUT_FAILED',
};

export default USER_ACTION_TYPES;
