const OTHER_USERS_ACTION_TYPE = {
  SEARCH_USERS_START: 'otherUsers/SEARCH_USERS_START',
  SEARCH_USERS_SUCCESS: 'otherUsers/SEARCH_USERS_SUCCESS',
  SEARCH_USERS_FAILED: 'otherUsers/SEARCH_USERS_FAILED',

  GET_USER_START: 'otherUsers/GET_USER_START',
  GET_USER_SUCCESS: 'otherUsers/GET_USER_SUCCESS',
  GET_USER_FAILED: 'otherUsers/GET_USER_FAILED',

  FOLLOW_USER_START: 'otherUsers/FOLLOW_USER_START',
  FOLLOW_USER_SUCCESS: 'otherUsers/FOLLOW_USER_SUCCESS',
  FOLLOW_USER_FAILED: 'otherUsers/FOLLOW_USER_FAILED',

  UNFOLLOW_USER_START: 'otherUsers/UNFOLLOW_USER_START',
  UNFOLLOW_USER_SUCCESS: 'otherUsers/UNFOLLOW_USER_SUCCESS',
  UNFOLLOW_USER_FAILED: 'otherUsers/UNFOLLOW_USER_FAILED',
};

export default OTHER_USERS_ACTION_TYPE;
